const colors = {
  light: {
    text: "#0f172a",
    tint: "#3b82f6",
    background: "#f8fafc",
    foreground: "#0f172a",
    card: "#ffffff",
    cardForeground: "#0f172a",
    primary: "#3b82f6",
    primaryForeground: "#ffffff",
    secondary: "#e2e8f0",
    secondaryForeground: "#334155",
    muted: "#f1f5f9",
    mutedForeground: "#64748b",
    accent: "#dbeafe",
    accentForeground: "#1d4ed8",
    destructive: "#ef4444",
    destructiveForeground: "#ffffff",
    success: "#22c55e",
    successForeground: "#ffffff",
    warning: "#f59e0b",
    warningForeground: "#ffffff",
    border: "#e2e8f0",
    input: "#e2e8f0",
    navBackground: "#0f172a",
    navForeground: "#f8fafc",
  },
  dark: {
    text: "#f8fafc",
    tint: "#60a5fa",
    background: "#0a0f1e",
    foreground: "#f8fafc",
    card: "#111827",
    cardForeground: "#f8fafc",
    primary: "#3b82f6",
    primaryForeground: "#ffffff",
    secondary: "#1e293b",
    secondaryForeground: "#cbd5e1",
    muted: "#1e293b",
    mutedForeground: "#94a3b8",
    accent: "#1e3a5f",
    accentForeground: "#93c5fd",
    destructive: "#ef4444",
    destructiveForeground: "#ffffff",
    success: "#22c55e",
    successForeground: "#ffffff",
    warning: "#f59e0b",
    warningForeground: "#ffffff",
    border: "#1e293b",
    input: "#1e293b",
    navBackground: "#060d1a",
    navForeground: "#f8fafc",
  },
  radius: 12,
};

export default colors;
